In [149]:
import numpy as np
import pickle as pkl
import matplotlib.pyplot as plt

In [150]:
import torch

In [151]:
from part1 import *

In [152]:
x = torch.randn(1,2)
shape=(2,0,1)
y = torch.randn(1,2)

In [158]:
print(y)
print(x)

tensor([[0.6105, 0.3210]])
tensor([[1.7283, 0.5568]])


In [154]:
def simple_concatenate(tensors):
    """
    TODO: Implement a function that concatenates the given sequence of tensors
        in the first dimension and returns the result
    """
    result = torch.cat(tensors,0)
    return result

In [155]:
simple_concatenate((x,y))

tensor([[1.7283, 0.5568],
        [0.6105, 0.3210]])